easy_admin:
    site_name: 'CMS<em style="font-size: 80%;">Base</em>'
    design:
        form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
    entities:
        User:
            class: App\Entity\User
            label: admin.menu.user.label
            controller: App\Controller\Admin\UserController
            list:
                dql_filter: "entity.roles NOT LIKE '%%ROLE_SUPER_ADMIN%%'"
                title: 'admin.user.list'
                fields:
                    - { property: 'id', label: 'admin.user.list.id'}
                    - { property: 'fullname', label: 'admin.user.list.fullname'}
                    - { property: 'active', label: 'admin.user.list.active'}
                    - { property: 'email', type: 'email', label: 'admin.user.list.email'}
                    - { property: 'roles', label: 'admin.user.list.roles'}
                sort: ['lastName', 'ASC']
                actions:
                    - { name: 'switch_user', icon: 'user-secret', type: 'route', label: '', title: 'admin.user.list.switch_user'}
                    - { name: 'edit', icon: 'pencil', label: '', title: 'admin.user.list.edit'}
                    - { name: 'delete', icon: 'trash', label: '', title: 'admin.user.list.delete' }
                    - { name: 'new', label: 'admin.user.new.button'}
                    - { name: 'search', label: 'admin.user.search.button'}
            new:
                title:  'admin.user.new'
                fields:
                    - { property: 'firstName'}
                    - { property: 'lastName'}
                    - { property: 'email', type: 'email', label: 'Email' }
                    - { property: 'password'}
                    - { property: 'active', label: 'Actif ?', type: 'checkbox'}
            edit:
                title:  'admin.user.edit'
                form:
                    fields:
                        - '-password'
                fields:
                    - { property: 'firstName'}
                    - { property: 'lastName'}
                    - { property: 'active', label: 'Actif ?', type: 'checkbox'}
                    - { property: 'username', type: 'email', label: 'Email' }
                    - { property: 'roles', type: choice, type_options: { expanded: true, multiple: true  }}